export const keyLayout = [
  '`',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '0',
  '-',
  '=',
  'Backspace',
  'Tab',
  'q',
  'w',
  'e',
  'r',
  't',
  'y',
  'u',
  'i',
  'o',
  'p',
  '[',
  ']',
  '\\',
  'DEL',
  'Caps Lock',
  'a',
  's',
  'd',
  'f',
  'g',
  'h',
  'j',
  'k',
  'l',
  ';',
  "'",
  'ENTER',
  'Shift',
  "''",
  'z',
  'x',
  'c',
  'v',
  'b',
  'n',
  'm',
  '.',
  ',',
  '/',
  'Up',
  'Shift',
  'Ctrl',
  'Win',
  'Alt',
  'space',
  'Alt',
  'Ctrl',
  'Left',
  'Down',
  'Right',
];

export const keys = [
  { en: '`', ru: 'ё', key: '`' },
  { en: '1', ru: '1', key: 'Digit1' },
  { en: '2', ru: '2', key: 'Digit2' },
  { en: '3', ru: '3', key: 'Digit3' },
  { en: '4', ru: '4', key: 'Digit4' },
  { en: '5', ru: '5', key: 'Digit5' },
  { en: '6', ru: '6', key: 'Digit6' },
  { en: '7', ru: '7', key: 'Digit7' },
  { en: '8', ru: '8', key: 'Digit8' },
  { en: '9', ru: '9', key: 'Digit9' },
  { en: '0', ru: '0', key: 'Digit0' },
  { en: '-', ru: '_', key: 'Minus' },
  { en: '=', ru: '=', key: 'Equal' },
  { en: 'Backspace', ru: 'Backspace', key: 'Backspace' },
  { en: 'Tab', ru: 'Tab', key: 'Tab' },
  { en: 'q', ru: 'й', key: 'KeyQ' },
  { en: 'w', ru: 'ц', key: 'KeyW' },
  { en: 'e', ru: 'у', key: 'KeyE' },
  { en: 'r', ru: 'к', key: 'KeyR' },
  { en: 't', ru: 'е', key: 'KeyT' },
  { en: 'y', ru: 'н', key: 'KeyY' },
  { en: 'u', ru: 'г', key: 'KeyU' },
  { en: 'i', ru: 'ш', key: 'KeyI' },
  { en: 'o', ru: 'щ', key: 'KeyO' },
  { en: 'p', ru: 'з', key: 'KeyP' },
  { en: '[', ru: 'х', key: 'BracketLeft' },
  { en: ']', ru: 'ъ', key: 'BracketRight' },
  { en: '\\', ru: '/', key: 'Backslash' },
  { en: 'DEL', ru: 'DEL', key: 'Delete' },
  { en: 'Caps Lock', ru: 'Caps Lock', key: 'CapsLock' },
  { en: 'a', ru: 'ф', key: 'KeyA' },
  { en: 's', ru: 'ы', key: 'KeyS' },
  { en: 'd', ru: 'в', key: 'KeyD' },
  { en: 'f', ru: 'а', key: 'KeyF' },
  { en: 'g', ru: 'п', key: 'KeyG' },
  { en: 'h', ru: 'р', key: 'KeyH' },
  { en: 'j', ru: 'о', key: 'KeyJ' },
  { en: 'k', ru: 'л', key: 'KeyK' },
  { en: 'l', ru: 'д', key: 'KeyL' },
  { en: ';', ru: 'ж', key: 'Semicolon' },
  { en: "'", ru: 'э', key: 'Quote' },
  { en: 'ENTER', ru: 'ENTER', key: 'Enter' },
  { en: 'Shift', ru: 'Shift', key: 'ShiftLeft' },
  { en: '"', ru: '"', key: '"' },
  { en: 'z', ru: 'я', key: 'KeyZ' },
  { en: 'x', ru: 'ч', key: 'KeyX' },
  { en: 'c', ru: 'с', key: 'KeyC' },
  { en: 'v', ru: 'м', key: 'KeyV' },
  { en: 'b', ru: 'и', key: 'KeyB' },
  { en: 'n', ru: 'т', key: 'KeyN' },
  { en: 'm', ru: 'т', key: 'KeyN' },
  { en: '.', ru: 'б', key: 'KeyN' },
  { en: ',', ru: 'ю', key: 'KeyN' },
  { en: '/', ru: '?', key: 'KeyN' },
  { en: 'Up', ru: 'Up', key: 'ArrowUp' },
  { en: 'Shift', ru: 'Shift', key: 'ShiftRight' },
  { en: 'Ctrl', ru: 'Ctrl', key: 'ControlLeft' },
  { en: 'Win', ru: 'Win', key: 'MetaLeft' },
  { en: 'Alt', ru: 'Alt', key: 'AltLeft' },
  { en: 'space', ru: 'space', key: 'Space' },
  { en: 'Alt', ru: 'Alt', key: 'AltRight' },
  { en: 'Ctrl', ru: 'Ctrl', key: 'CtrlRight' },
  { en: 'Left', ru: 'Left', key: 'ArrowLeft' },
  { en: 'Down', ru: 'Down', key: 'ArrowDown' },
  { en: 'Right', ru: 'Right', key: 'ArrowRight' },
];
